import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import 'pretendard/dist/web/variable/pretendardvariable-dynamic-subset.css'
// import '@/styles/global.scss'
import "./globals.css";

import Header from '@/components/Header'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  title: { 
    // template: '%s | 사이트이름', 
    template: '[Test] %s | Create Next App', 
    default: '사이트이름'
  },
  description: "Generated by create next app",
  // Open Graph Protocol / <meta property="og:속성" content="값">
  openGraph: {
    type: 'website',
    siteName: '사이트 이름',
    title: '페이지 제목',
    description: '페이지 설명',
    images: '페이지 대표 이미지'
  },
  // Twitter Cards / <meta name="twitter:속성" content="값">
  twitter: {
    card: 'summary_large_image',
    site: '사이트 이름',
    title: '페이지 제목',
    description: '페이지 설명',
    images: '페이지 대표 이미지'
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="p-2">{children}</main>
      </body>
    </html>
  );
}
