import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Sidebar from '@/components/Sidebar'
import { getUserSession } from '@/app/auth/actions' // Import getUserSession

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) { // Make RootLayout async
  const user = await getUserSession(); // Fetch user session

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          <Sidebar user={user} /> {/* Pass user as prop to Sidebar */}
          <div className="flex-1">
            <Header />
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  )
}
